---
version: "3.8"
services:
  backend:
    build: ./10-calendar-backend
    container_name: calendar-backend
    ports:
      - 4000:4000
    restart: unless-stopped
    env_file:
      - ./10-calendar-backend/.env
  frontend:
    build: ./10-calendar
    container_name: calendar-frontend
    ports:
      - 80:80
    depends_on:
      - backend
    restart: unless-stopped
